# Generated by Django 6.0 on 2025-12-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
    ]
