# Generated by Django 6.0 on 2026-01-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_review_stars_alter_review_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="stars",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=10
            ),
        ),
    ]
